/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { Sias } from "./Sias";
export type { SiasGovernor } from "./SiasGovernor";
export type { SiasTimelock } from "./SiasTimelock";
export type { SiasTreasury } from "./SiasTreasury";
