/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { Sias__factory } from "./Sias__factory";
export { SiasGoverner__factory } from "./SiasGoverner__factory";
