import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import ConnectWallet from "../components/ConnectWallet";
import Balance from '../components/Balance';
import TransferFund from '../components/Transfer';

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Sias Vote</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

   <main>
      <br></br>
          <ConnectWallet />
        <br></br>
          <Balance />
        <br></br>
        <TransferFund />
      
        <div>Fund In Treasury</div>
        <div>Release Fund from Treasury</div>
        <div>Create Proposal</div>
        <div>Current Stage of Proposal</div>
        <div>Proposal Deadline</div>
        <div>Current Blocknumber</div>
        <div>Number of Votes Reuired to pass </div>
        <div>Cast A Vote</div>
        <div>Vote For</div>
        <div>Votes In Against</div>
        <div>Votes In Favor</div>
        <div>Votes In Neutral</div>
   </main>
    </div>
  )
}

export default Home
